language: go
go:
  - 1.5
  - 1.6
  - tip
install:
  - export GOPATH="$HOME/gopath"
  - mkdir -p "$GOPATH/src/github.com/Harvey-OS/ninep"
  - go get -v -t -d github.com/Harvey-OS/ninep/...
script:
  - go test github.com/Harvey-OS/ninep/...
